version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portfolio
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    container_name: flask_app
    image: stefan/flask_app:1.0
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/portfolio
      JWT_SECRET_KEY: slbodvmvs
      MAIL_USERNAME: schneiderelectricinternship@gmail.com
      MAIL_PASSWORD: aeoo vuqm gifg pnsw
      MAIL_DEFAULT_SENDER: schneiderelectricinternship@gmail.com

volumes:
  db_data: